# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/vivado/ECOP-18340161-04/ECOP-18340161-04.cache/wt [current_project]
set_property parent.project_path E:/vivado/ECOP-18340161-04/ECOP-18340161-04.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/updatePC.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/keep_control.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/SignZeroExtend.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/Shifter.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/Register_File.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/PC.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/MEM_WB.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/Instruction_Memory.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/Instruction_Divided.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/IF_ID.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/ID_EX.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/HazardDetect_Unit.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/Forward_Unit.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/EX_MEM.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/DS_32_3.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/data_select_5_3.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/data_select_32_2.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/Data_Mem.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/Control_Unit.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/br_control.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/ALUSrcB_Select.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/ALU.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/add_const.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/PipeLineCPU.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/key_vibration.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/SegLED.v
  E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/sources_1/new/Basys3.v
}
read_xdc E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/constrs_1/new/my.xdc
set_property used_in_implementation false [get_files E:/vivado/ECOP-18340161-04/ECOP-18340161-04.srcs/constrs_1/new/my.xdc]

synth_design -top Basys3 -part xc7a35tcpg236-1
write_checkpoint -noxdef Basys3.dcp
catch { report_utilization -file Basys3_utilization_synth.rpt -pb Basys3_utilization_synth.pb }
